spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbhrp?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: MySQL
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: false
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:      
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb
        

    
server:
  port: 8081
  
  
  
  